[package]
name = "rustbot"
version = "0.2.0"
authors = ["Michael Lingo <spartan364@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "*"
serde_json = "*"
serde = "*"
regex = "*"
lazy_static = "*"
simple-error = "*"
unicode-normalization = "*"
serenity = "*"
rand = "*"
strsim = "*"
chrono = "*"

[profile.release]
lto = true