unstable_features = true
max_width = 100
newline_style = "Unix"
merge_imports = true
normalize_doc_attributes = true
normalize_comments = true
reorder_impl_items = true
empty_item_single_line = true
format_strings = true